version: '2'

services:
  collate-attributes:
    build: 
      context: ./collate-attributes
    volumes:
      - ./data:/data

  collate-efo:
    build:
      context: ./collate-efo
    volumes:
      - ./data:/data

  #takes about 45min
  create-csv:
    build: 
      context: ./create-csv
    volumes:
      - ./data:/data

  populate-neo4j:
    build: 
      context: ./populate-neo4j
    volumes:
      - ./data:/data
    
  neo4j-server-local:
    image: neo4j:3.0.6
    environment:
        NEO4J_AUTH: none
    volumes:
        - ./data:/data
        - ./neo4j-server-local/conf:/conf
    ports:
        - "7473:7473"
        - "7474:7474"
        - "7687:7687"
#    command: dump-config

  #to run this container use a command like:
  #docker-compose run --service-ports neo4j-analysis [ARGS]
  neo4j-analysis:
    build: 
      context: ./neo4j-analysis
    volumes:
      - ./neo4j-analysis:/neo4j-analysis
    depends_on:
      - neo4j-server-local
    entrypoint:
      - ./wait-for-it.sh
      - neo4j-server-local:7474
      - --
      - python
      - -u
      - neo4j-analysis/neo4j-analysis.py
    
    
