version: '2'

services:
  collate-attributes:
    build: 
      context: ./collate-attributes
    volumes:
      - ./data:/data

  create-csv:
    build: 
      context: ./create-csv
    volumes:
      - ./data:/data

  populate-neo4j:
    build: 
      context: ./populate-neo4j
    volumes:
      - ./data:/data
    
  neo4j-server:
    build: 
      context: .
      dockerfile: ./neo4j-server/Dockerfile
    image: biosamples:neo4j-server
    environment:
        NEO4J_AUTH: none
    ports:
        - "7474:7474"
        - "7687:7687"
    
  neo4j-server-local:
    image: neo4j:3.0.6
    environment:
        NEO4J_AUTH: none
    volumes:
      - ./data:/data
    ports:
        - "7474:7474"
        - "7687:7687"
    
    
#allowing docker-compose to create a new network can break internal connectivty on host  
#networks:
#  default:
#    external:
#      name: bridge
