version: '2'

services:
  collate-attributes:
    build: 
      context: ./collate-attributes
    volumes:
      - ./data:/data
    
  neo4j-server:
    image: neo4j:latest
    volumes:
      - ./data:/data
    environment:
      NEO4J_AUTH: none
    expose:
      - "7474"
      - "7687"
    network_mode: "host"
    
    
#allowing docker-compose to create a new network can break internal connectivty on host  
networks:
  default:
    external:
      name: bridge
