version: '2'

services:
  collate-attributes:
    build: 
      context: ./collate-attributes
    volumes:
      - ./data:/data

  create-csv:
    build: 
      context: ./create-csv
    volumes:
      - ./data:/data
      - ./output:/output

  populate-neo4j:
    build: 
      context: ./populate-neo4j
    volumes:
      - ./output:/output
    
  neo4j-server:
    image: neo4j:3.0.6
    volumes:
      - ./output/graph.db:/data/databases/graph.db
    environment:
      NEO4J_AUTH: none
    ports:
        - "7474:7474"
    
    
#allowing docker-compose to create a new network can break internal connectivty on host  
#networks:
#  default:
#    external:
#      name: bridge
